tasks:
  - init: cargo build
    name: build
  - init: cargo test
    openMode: split-right
    name: test
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
vscode:
  extensions:
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
